<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Authors>Rafael Mac Menz</Authors>
		<Company>McMenz IT</Company>
		<Description>A .NET 10.0 collection with value objects that model Brazilian person domain properties</Description>
		<NeutralLanguage>pt-BR</NeutralLanguage>
		<RepositoryUrl>https://github.com/m4cm3nz/Person.Model.ValueObjects</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>value-object cnpj cpf mobile landline cardnumber luhn brazil brazilian person</PackageTags>
		<PackageReleaseNotes>See CHANGELOG.md</PackageReleaseNotes>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<PackageProjectUrl>https://github.com/m4cm3nz/Person.Model.ValueObjects</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Version>10.0.1</Version>
		<AssemblyVersion>10.0.1.0</AssemblyVersion>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
		<None Include="..\CHANGELOG.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
